---
- name: Set task type(command)
  ansible.builtin.set_fact:
    task_name: 'gathering_definition_task_command.yml'
  when:
    - parameter.type == 'command'

- name: Set task type(shell)
  ansible.builtin.set_fact:
    task_name: 'gathering_definition_task_shell.yml'
  when:
    - parameter.type == 'shell'

- name: Set task type(file transfer)
  ansible.builtin.set_fact:
    task_name: 'gathering_definition_task_file.yml'
  when:
    - parameter.type == 'file' or parameter.type == 'directory'
